version: '3.8'
services:
  one4all:
    build: ./one4all_webserver/
    ports:
      - '3000:3000'
    volumes:
      - './one4all_webserver:/app'
      - ./node-tools:/app/node_modules/node-tools
    environment:
      - PRIMARY_API_HOSTNAME=${PRIMARY_API_HOSTNAME}
      - SECONDARY_API_HOSTNAME=${SECONDARY_API_HOSTNAME}
      - QUEUE_SERVER_HOSTNAME=${QUEUE_SERVER_HOSTNAME}
      - IS_SYNC=${IS_SYNC}
      - QUEUE_NAME=${QUEUE_NAME}
    networks:
      - one4all-network
  primary_api:
    build: ./primary_api/
    container_name: ${PRIMARY_API_HOSTNAME}
    environment:
      - QUEUE_SERVER_HOSTNAME=${QUEUE_SERVER_HOSTNAME}
      - IS_SYNC=${IS_SYNC}
      - QUEUE_NAME=${QUEUE_NAME}
    ports:
      - '3001:3000'
    volumes:
    - ./primary_api:/app
    - ./node-tools:/app/node_modules/node-tools
    networks:
      - one4all-network
    depends_on:
      - rabbitmq
  secondary_api:
    build: ./secondary_api/
    container_name: ${SECONDARY_API_HOSTNAME}
    environment:
      - QUEUE_SERVER_HOSTNAME=${QUEUE_SERVER_HOSTNAME}
      - IS_SYNC=${IS_SYNC}
      - QUEUE_NAME=${QUEUE_NAME}
    ports:
      - '3002:3000'
    volumes:
      - './secondary_api:/app'
      - ./node-tools:/app/node_modules/node-tools
    networks:
      - one4all-network
  rabbitmq:
      image: rabbitmq:3.11.8-management-alpine
      container_name: ${QUEUE_SERVER_HOSTNAME}
      ports: 
      - 15672:15672
      - 5672:5672
      networks:
      - one4all-network
networks:
  one4all-network:
    driver: bridge
    ipam:
     config:
       - subnet: 10.11.0.0/16
         gateway: 10.11.0.1
