version: '3.8'
services:
  one4all:
    build: ./one4all_webserver/
    ports:
      - '3000:3000'
    volumes:
      - './one4all_webserver:/app'
    environment:
      - PRIMARY_API_HOSTNAME=primary_api
      - SECONDARY_API_HOSTNAME=secondary_api
    networks:
      - one4all-network
  primary_api:
    build: ./primary_api/
    container_name: primary_api
    ports:
      - '3001:3001'
    volumes:
      - './primary_api:/app'
    networks:
      - one4all-network
  secondary_api:
    build: ./secondary_api/
    container_name: secondary_api
    ports:
      - '3002:3002'
    volumes:
      - './secondary_api:/app'
    networks:
      - one4all-network
networks:
  one4all-network:
    driver: bridge
    ipam:
     config:
       - subnet: 10.11.0.0/16
         gateway: 10.11.0.1